<?php
/**
 * This bean shell has been generated by CRT tools using : 
 * tools/bean.php name=planet attributes=id,user,type,name,age,terraFormed,water,oxygen,ground,itrium,forest,civilisation database=game
 * !!! Do not edit it this file manually !!!
 * 
 * Sincerely, 
 * CRT
 */
class PlanetShell extends Bean {

	protected $database = "game";

	protected $id;
	protected $user;
	protected $type;
	protected $name;
	protected $age;
	protected $terraFormed;
	protected $water;
	protected $oxygen;
	protected $ground;
	protected $itrium;
	protected $forest;
	protected $civilisation;

	public function getId() {
		return $this->id;
	}

	public function setId($value) {
		$this->markModified('id');
		$this->id = $value;
	}

	public function getUser() {
		return $this->user;
	}

	public function setUser($value) {
		$this->markModified('user');
		$this->user = $value;
	}

	public function getType() {
		return $this->type;
	}

	public function setType($value) {
		$this->markModified('type');
		$this->type = $value;
	}

	public function getName() {
		return $this->name;
	}

	public function setName($value) {
		$this->markModified('name');
		$this->name = $value;
	}

	public function getAge() {
		return $this->age;
	}

	public function setAge($value) {
		$this->markModified('age');
		$this->age = $value;
	}

	public function getTerraFormed() {
		return $this->terraFormed;
	}

	public function setTerraFormed($value) {
		$this->markModified('terraFormed');
		$this->terraFormed = $value;
	}

	public function getWater() {
		return $this->water;
	}

	public function setWater($value) {
		$this->markModified('water');
		$this->water = $value;
	}

	public function getOxygen() {
		return $this->oxygen;
	}

	public function setOxygen($value) {
		$this->markModified('oxygen');
		$this->oxygen = $value;
	}

	public function getGround() {
		return $this->ground;
	}

	public function setGround($value) {
		$this->markModified('ground');
		$this->ground = $value;
	}

	public function getItrium() {
		return $this->itrium;
	}

	public function setItrium($value) {
		$this->markModified('itrium');
		$this->itrium = $value;
	}

	public function getForest() {
		return $this->forest;
	}

	public function setForest($value) {
		$this->markModified('forest');
		$this->forest = $value;
	}

	public function getCivilisation() {
		return $this->civilisation;
	}

	public function setCivilisation($value) {
		$this->markModified('civilisation');
		$this->civilisation = $value;
	}

}
